sudo: false
language: node_js
branches:
  only: master
node_js:
  - '8'
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run compile
  - npm run test
  - npm run lint
  - npm run coveralls
